import "./globals.css";
import "./reset.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "SMK - Statens Museum for Kunst",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="da">
      <body>
        <header>
          <Header />
        </header>
        <main className="mt-25">
          {children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
