import "./globals.css";
import "./reset.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";

export const metadata = {
  title: "SMK - Statens Museum for Kunst",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body>
        <header>
          <Header />
        </header>
        <main className="mt-35">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
