import "./globals.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";

export const metadata = {
  title: "SMK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
